baseURL: https://aurbano.eu
disablePathToLower: true
languageCode: en-us
title: Alejandro U. Alvarez

params:
  author: "Alejandro U. Alvarez"
  description: "I sometimes stop by"
  profilePic: https://avatars.githubusercontent.com/u/2827818?v=4
  githubUsername: "aurbano"
  repo: https://github.com/aurbano/aurbano.eu
  font: "Raleway"
  highlight: true
  highlightStyle: "dark"
  highlightLanguages: ["javascript", "typescript", "java", "haskell", "bash"]

outputs:
  home:
  - HTML
  - RSS
  - JSON

taxonomies:
  post: posts
  category: categories
  tag: tags

menu:
  main:
    - url: /about/
      name: About
      weight: 2
    - url: /post/
      name: Posts
      weight: 3
    - url: /projects/
      name: Projects
      weight: 4
  icon:
    - url: 'https://github.com/aurbano/'
      name: github
      weight: 2
    - url: 'https://www.linkedin.com/in/aurbano/'
      name: linkedin
      weight: 3
    - url: 'https://twitter.com/alalex'
      name: twitter
      weight: 4
    - url: 'https://stackoverflow.com/users/1262824/aurbano'
      name: stack-overflow
      weight: 5
    - url: 'https://news.ycombinator.com/user?id=aurbano'
      name: hacker-news
      weight: 6
    - url: '/index.xml'
      name: rss
      weight: 7

markup:
  goldmark:
    renderer:
      unsafe: true
